### ISSUE TITLE
加载模型出错-RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by skywoodlin** [CheshireCC/faster-whisper-GUI#96]
win10, nvidia 2070显卡， 加载模型： whisper-large-v3-float32

`处理设备`中选择`auto`或`cpu`都没问题， 但是发现是使用cpu进行转换的， 不喜欢。
于是查了一下， `处理设备`中选择`cuda`, 加载时出现如题错误(fasterWhispergui.log中)。

小白第一次搞， 机器上之前装了python的各种版本， cmd中运行`python -V`输出： `Python 3.9.1`

**Comment by CheshireCC** [comment]
不需要python，运行环境已经编译进 exe 程序里面了，你这个问题应该是安装了

**Comment by CheshireCC** [comment]
不需要python，运行环境已经编译进 exe 程序里面了，你这个问题应该是安装了 0.6.0 以后的版本造成的，更新显卡驱动应该会有帮助

**Comment by skywoodlin** [comment]
> 不需要python，运行环境已经编译进 exe 程序里面了，你这个问题应该是安装了 0.6.0 以后的版本造成的，更新显卡驱动应该会有帮助

只能下载0.5.9了， 亲测已解决， 谢谢
